name: placetest_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.5.4=py37h14c3975_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py37_1003
  - async-timeout=3.0.1=py_1000
  - attrs=19.1.0=py_0
  - bcrypt=3.1.6=py37h516909a_1
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_8
  - biopython=1.74=py37h516909a_0
  - boto3=1.9.213=py_0
  - botocore=1.12.213=py_0
  - bwidget=1.9.11=0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - configargparse=0.13.0=py_1
  - cryptography=2.7=py37h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - datrie=0.8=py37h516909a_0
  - decorator=4.4.0=py_0
  - docutils=0.15.2=py37_0
  - dropbox=9.4.0=py_0
  - epa-ng=0.3.5=he860b03_0
  - expat=2.2.5=he1b5a44_1003
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - ftputil=3.4=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_8
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_8
  - gitdb2=2.0.5=py_0
  - gitpython=3.0.2=py_0
  - glib=2.58.3=h6f030ca_1002
  - google-api-core=1.14.2=py37_0
  - google-auth=1.6.3=py_0
  - google-cloud-core=1.0.3=py_0
  - google-cloud-storage=1.18.0=py_0
  - google-resumable-media=0.3.2=py_0
  - googleapis-common-protos=1.6.0=py37_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h5933667_1
  - gsl=2.5=h294904e_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_8
  - harfbuzz=2.4.0=h9f30f68_2
  - hmmer=3.2.1=hf484d3e_1
  - icu=64.2=he1b5a44_0
  - idna=2.8=py37_1000
  - java-jdk=8.0.112=1
  - jinja2=2.10.1=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.2=py37_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_1
  - libprotobuf=3.9.1=h8b12597_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_2
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.2.1=h14c3975_2004
  - markupsafe=1.1.1=py37h14c3975_0
  - mpi=1.0=openmpi
  - multidict=4.5.2=py37h14c3975_1000
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - numpy=1.17.0=py37h95a1406_0
  - openjdk=8.0.112=zulu8.19.0.1_3
  - openmpi=3.1.4=hc99cbb1_0
  - openssl=1.1.1c=h516909a_0
  - pandas=0.25.0=py37hb3f55d8_0
  - pango=1.42.4=ha030887_1
  - paramiko=2.6.0=py37_0
  - pcre=8.41=hf484d3e_1003
  - phyml=3.3.20190321=h14c3975_1
  - pip=19.2.2=py37_0
  - pixman=0.38.0=h516909a_1003
  - pplacer=1.1.alpha19=1
  - prettytable=0.7.2=py_3
  - protobuf=3.9.1=py37he1b5a44_0
  - psutil=5.6.3=py37h516909a_0
  - psycopg2=2.8.3=py37h72c5cf5_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.6=py_0
  - pyasn1-modules=0.2.6=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pygraphviz=1.3=py37h14c3975_1
  - pynacl=1.3.0=py37h14c3975_1000
  - pyopenssl=19.0.0=py37_0
  - pyrsistent=0.15.4=py37h516909a_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - r=3.6=r36_1003
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.4=r36hcdcec82_1
  - r-base=3.6.1=hba50c9b_4
  - r-boot=1.3_23=r36h6115d3f_2
  - r-cairo=1.5_10=r36hcdcec82_1
  - r-class=7.3_15=r36hcdcec82_1001
  - r-cli=1.1.0=r36h6115d3f_1
  - r-cluster=2.1.0=r36h9bbef5b_2
  - r-codetools=0.2_16=r36h6115d3f_1001
  - r-colorspace=1.4_1=r36hcdcec82_1
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-digest=0.6.20=r36h0357c0b_1
  - r-ellipsis=0.2.0.1=r36hcdcec82_1
  - r-fansi=0.4.0=r36hcdcec82_1001
  - r-foreign=0.8_71=r36hcdcec82_1003
  - r-ggplot2=3.2.1=r36h6115d3f_0
  - r-glue=1.3.1=r36hcdcec82_1
  - r-gridbase=0.4_7=r36h6115d3f_1002
  - r-gtable=0.3.0=r36h6115d3f_2
  - r-kernsmooth=2.23_15=r36h9bbef5b_1004
  - r-labeling=0.3=r36h6115d3f_1002
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-lazyeval=0.2.2=r36hcdcec82_1
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-mass=7.3_51.4=r36hcdcec82_1
  - r-matrix=1.2_17=r36hcdcec82_1
  - r-mgcv=1.8_28=r36hcdcec82_1
  - r-munsell=0.5.0=r36h6115d3f_1002
  - r-nlme=3.1_141=r36h9bbef5b_1
  - r-nnet=7.3_12=r36hcdcec82_1003
  - r-pillar=1.4.2=r36h6115d3f_2
  - r-pkgconfig=2.0.2=r36h6115d3f_1002
  - r-plyr=1.8.4=r36h0357c0b_1003
  - r-r6=2.4.0=r36h6115d3f_2
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1002
  - r-rcpp=1.0.2=r36h0357c0b_0
  - r-recommended=3.6=r36_1003
  - r-reshape2=1.4.3=r36h0357c0b_1004
  - r-rlang=0.4.0=r36hcdcec82_1
  - r-rpart=4.1_15=r36hcdcec82_1
  - r-scales=1.0.0=r36h0357c0b_1002
  - r-spatial=7.3_11=r36hcdcec82_1003
  - r-stringi=1.4.3=r36h0e574ca_3
  - r-stringr=1.4.0=r36h6115d3f_1
  - r-survival=2.44_1.1=r36hcdcec82_1
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-vctrs=0.2.0=r36hcdcec82_1
  - r-viridislite=0.3.0=r36h6115d3f_1002
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - ratelimiter=1.2.0=py37_1000
  - raxml=8.2.12=h14c3975_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - rsa=3.4.2=py_1
  - s3transfer=0.2.1=py37_0
  - sed=4.7=h1bed415_1000
  - setuptools=41.2.0=py37_0
  - six=1.12.0=py37_1000
  - smmap2=2.0.5=py_0
  - snakemake=5.5.4=1
  - snakemake-minimal=5.5.4=py_1
  - sqlalchemy=1.3.7=py37h516909a_0
  - sqlite=3.29.0=hcee41ef_0
  - taxtastic=0.8.11=py_0
  - tk=8.6.9=hed695b0_1002
  - tktable=2.10=h555a92e_1
  - urllib3=1.25.3=py37_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xlrd=1.2.0=py_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py37h14c3975_1000
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - dendropy==4.4.0
    - fastalite==0.3
    - psycopg2-binary==2.8.3
