name: PEWO
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rappas
  - epa-ng
  - pplacer
  - dendropy
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.6.2=py36h516909a_0
  - alsa-lib=1.1.5=h516909a_1002
  - ant=1.10.0=0
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - bcrypt=3.1.7=py36h516909a_0
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_16
  - biopython=1.76=py36h516909a_0
  - boto3=1.12.1=py_0
  - botocore=1.15.1=py_0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - configargparse=1.0=py_0
  - cryptography=2.8=py36h72c5cf5_1
  - curl=7.68.0=hf8cf82a_0
  - datrie=0.8=py36h516909a_0
  - decorator=4.4.1=py_0
  - docutils=0.15.2=py36_0
  - dropbox=9.4.0=py_0
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - fonts-conda-forge=1=0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - ftputil=3.4=py_0
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_16
  - gdk-pixbuf=2.38.2=h3f25603_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_16
  - ghostscript=9.22=hf484d3e_1001
  - giflib=5.2.1=h516909a_1
  - gitdb2=3.0.2=py_0
  - gitpython=3.0.5=py_0
  - glib=2.58.3=py36h6f030ca_1002
  - gmp=6.2.0=he1b5a44_1
  - gobject-introspection=1.58.2=py36h5503ade_1002
  - google-api-core=1.16.0=py36_1
  - google-auth=1.11.2=py_0
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.26.0=py_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py36_1
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - gsl=2.5=h294904e_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_16
  - harfbuzz=2.4.0=h9f30f68_3
  - hmmer=3.3=he1b5a44_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - imagemagick=7.0.9_24=pl526ha9fe49d_0
  - importlib_metadata=1.5.0=py36_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h14c3975_2001
  - jinja2=2.11.1=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py36_0
  - jupyter_core=4.6.2=py36_0
  - krb5=1.16.4=h2fd8d38_0
  - lcms2=2.9=hbd6801e_1
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.8.0=h8b12597_0
  - librsvg=2.46.4=h33a7fed_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.2.1=h14c3975_2004
  - markupsafe=1.1.1=py36h516909a_0
  - mpi=1.0=openmpi
  - multidict=4.7.4=py36h516909a_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_0
  - numpy=1.18.1=py36h95a1406_0
  - openjdk=11.0.1=h600c080_1018
  - openjpeg=2.3.1=h981e76c_3
  - openmpi=4.0.2=hdf1f1ad_3
  - openssl=1.1.1d=h516909a_0
  - paml=4.9=h516909a_5
  - pandas=1.0.1=py36hb3f55d8_0
  - pango=1.42.4=ha030887_1
  - paramiko=2.7.1=py36_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - phyml=3.3.20190909=h516909a_0
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - protobuf=3.8.0=py36he1b5a44_2
  - psutil=5.6.7=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py36_1
  - pygments=2.5.2=py_0
  - pygraphviz=1.3.1=py36_0
  - pynacl=1.3.0=py36h516909a_1001
  - pyopenssl=19.1.0=py36_0
  - pyrsistent=0.15.7=py36h516909a_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py36_0
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py36h516909a_0
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.5=r36hcdcec82_0
  - r-base=3.6.1=h3a67422_6
  - r-cairo=1.5_10=r36hcdcec82_1
  - r-cli=2.0.1=r36h6115d3f_0
  - r-colorspace=1.4_1=r36hcdcec82_1
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-data.table=1.12.8=r36hcdcec82_0
  - r-digest=0.6.24=r36h0357c0b_0
  - r-ellipsis=0.3.0=r36hcdcec82_0
  - r-fansi=0.4.1=r36hcdcec82_0
  - r-farver=2.0.3=r36h0357c0b_0
  - r-ggplot2=3.2.1=r36h6115d3f_0
  - r-glue=1.3.1=r36hcdcec82_1
  - r-gtable=0.3.0=r36h6115d3f_2
  - r-labeling=0.3=r36h6115d3f_1002
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-lazyeval=0.2.2=r36hcdcec82_1
  - r-lifecycle=0.1.0=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-mass=7.3_51.5=r36hcdcec82_0
  - r-matrix=1.2_18=r36hcdcec82_1
  - r-mgcv=1.8_31=r36hcdcec82_0
  - r-munsell=0.5.0=r36h6115d3f_1002
  - r-nlme=3.1_144=r36h9bbef5b_0
  - r-pillar=1.4.3=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_0
  - r-plyr=1.8.5=r36h0357c0b_0
  - r-r6=2.4.1=r36h6115d3f_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1002
  - r-rcpp=1.0.3=r36h0357c0b_0
  - r-reshape2=1.4.3=r36h0357c0b_1004
  - r-rlang=0.4.4=r36hcdcec82_0
  - r-scales=1.1.0=r36h6115d3f_0
  - r-stringi=1.4.6=r36h0e574ca_0
  - r-stringr=1.4.0=r36h6115d3f_1
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-vctrs=0.2.2=r36hcdcec82_0
  - r-viridislite=0.3.0=r36h6115d3f_1002
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - ratelimiter=1.2.0=py36_1000
  - raxml=8.2.12=h14c3975_1
  - raxml-ng=0.9.0=h192cbe9_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py36_0
  - sed=4.7=h1bed415_1000
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - smmap2=2.0.5=py_0
  - snakemake=5.10.0=0
  - snakemake-minimal=5.10.0=py_0
  - sqlalchemy=1.3.13=py36h516909a_0
  - sqlite=3.30.1=hcee41ef_0
  - taxtastic=0.8.11=py_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - toposort=1.5=py_3
  - traitlets=4.3.3=py36_0
  - typing_extensions=3.7.4.1=py36_0
  - urllib3=1.25.7=py36_0
  - wheel=0.34.2=py_1
  - wrapt=1.12.0=py36h516909a_0
  - xlrd=1.2.0=py_0
  - xmlrunner=1.7.7=py_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - yarl=1.3.0=py36h516909a_1000
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - apples
    - psycopg2-binary==2.8.4
    - treeswift==1.1.5
    - fastalite==0.3